### PR TITLE
Update rautomation.gemspec

### PR DESCRIPTION
**Pull request by pradeep2304**
@jarmo Could you review and merge the code

### CODE REVIEW

**Comment by jarmo** [comment]
Do RAutomation specs pass for you when upgrading FFI? I see segfault with `ruby 2.5.3p105 (2018-10-18 revision 65156) [i386-mingw32]`.

**Comment by jarmo** [comment]
Any information regarding this?

**Comment by pradeep2304** [comment]
No Jarmo.
Thank you

Regards,
Pradeep.

**Comment by jarmo** [comment]
Done in version 1.0.0

**Pull request closed without merging**
